server:
  port: 8080
spring:
  application:
    name: blog

  datasource:
    url: ${DBMS_DATABASE}
    username: ${DBMS_USERNAME}
    password: ${DBMS_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 30000
      validation-timeout: 5000
      auto-commit: false

  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
    properties:
      hibernate:
        jdbc.time_zone: UTC
        enable_lazy_load_no_trans: true
        connection.provider_disables_autocommit: true
        connection.handling_mode: DELAYED_ACQUISITION_AND_RELEASE_AFTER_TRANSACTION

  jackson:
    serialization:
      indent-output: true
  threads:
    virtual:
      enabled: true

logging:
  level:
    org:
      hibernate:
        orm:
          connections:
            pooling: ERROR
    net:
      ttddyy:
        dsproxy:
          listener: debug

