server:
  port: 8080

spring:
  application:
    name: blog

  datasource:
    url: ${DBMS_DATABASE}
    username: ${DBMS_USERNAME}
    password: ${DBMS_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 30000
      validation-timeout: 5000
      auto-commit: false

  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
    properties:
      hibernate:
        jdbc.time_zone: UTC
        enable_lazy_load_no_trans: true
        connection.provider_disables_autocommit: true
        connection.handling_mode: DELAYED_ACQUISITION_AND_RELEASE_AFTER_TRANSACTION

  jackson:
    serialization:
      indent-output: true
  threads:
    virtual:
      enabled: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL}
    password: ${EMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  flyway:
    enabled: true
    baseline-on-migrate: false
    locations: classpath:db/migration
    validate-on-migrate: true
  data:
    redis:
      port: 6379
      host: 127.0.0.1



cloudinary:
  cloud-name: ${CLOUD_NAME}
  api-key: ${API_KEY}
  api-secret: ${API_SECRET}


logging:
  level:
    org:
      hibernate:
        orm:
          connections:
            pooling: ERROR
    net:
      ttddyy:
        dsproxy:
          listener: debug


api:
 prefix: /api/v1


email:
  subject: "Welcome to the knowledge sharing system"
  content: "Now you can post to share your knowledge with everyone"

key:
  expiration:
    otp: 60
  change-password:
    expire: 600

# security
security:
  jwt:
    private-key: classpath:certs/private.pem
    public-key: classpath:certs/public.pem

token:
  access-duration: 3600       # 1 giờ
  refresh-duration: 604800    # 7 ngày

